name: seminar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.3.0
  cloud_firestore: 4.1.0
  firebase_storage: 11.0.6
  firebase_auth: ^4.1.4
  image_picker: 0.8.6
  path_provider: 2.0.11
  convex_bottom_bar: 3.1.0+1
  intl: 0.17.0
  flutter_barcode_scanner: 2.0.0
  qr_flutter: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

